---
- name: Ensure apt cache refreshed
  apt:
    update_cache: yes

- name: Install Java (OpenJDK 17)
  apt:
    name: openjdk-17-jdk
    state: present

- name: Install Tomcat (we'll use Tomcat 9 via apt)
  apt:
    name: tomcat9
    state: present

- name: Ensure Tomcat is running
  service:
    name: tomcat9
    state: started
    enabled: yes

- name: Install nginx
  apt:
    name: nginx
    state: present

- name: Configure Nginx as reverse proxy for Tomcat
  copy:
    dest: /etc/nginx/sites-available/petclinic
    content: |
      server {
          listen 80;
          location / {
              proxy_pass http://127.0.0.1:8080/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;
          }
      }
  notify: reload nginx

- name: Enable nginx site
  file:
    src: /etc/nginx/sites-available/petclinic
    dest: /etc/nginx/sites-enabled/petclinic
    state: link

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: reload nginx

- name: Create Tomcat setenv.sh with DB connection properties
  template:
    src: setenv.sh.j2
    dest: /etc/tomcat9/setenv.sh
    owner: root
    mode: '0755'
  vars:
    db_host: "{{ hostvars[groups['db'][0]]['ansible_host'] | default(hostvars[groups['db'][0]]['inventory_hostname']) }}"
    db_port: 3306
    db_name: petclinic
    db_user: petclinic
    db_pass: petclinic

- name: Upload petclinic.war to Tomcat webapps
  copy:
    src: ../../../../spring-framework-petclinic/target/petclinic.war
    dest: /var/lib/tomcat9/webapps/petclinic.war
    owner: tomcat
    group: tomcat
    mode: '0644'
  notify: restart tomcat

- name: Wait for app to be deployed (Tomcat auto-deploy)
  wait_for:
    host: 127.0.0.1
    port: 8080
    delay: 5
    timeout: 120

handlers:
  - name: reload nginx
    service:
      name: nginx
      state: reloaded

  - name: restart tomcat
    service:
      name: tomcat9
      state: restarted
