---
- name: Update apt cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install MySQL server
  apt:
    name: mysql-server
    state: present

- name: Ensure MySQL service is running
  service:
    name: mysql
    state: started
    enabled: yes

- name: Allow remote access (bind to 0.0.0.0)
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'
    backup: yes
  notify: restart mysql

- name: Create database and user for petclinic
  mysql_db:
    name: petclinic
    state: present

- name: Create MySQL user
  mysql_user:
    login_user: root
    name: petclinic
    password: petclinic
    priv: 'petclinic.*:ALL'
    host: '%'
    state: present

- name: Ensure MySQL root auth plugin is native (if Ubuntu default uses auth_socket)
  block:
    - name: Set root password (only if needed) - WARN: run interactively if secure
      mysql_user:
        login_user: root
        name: root
        host_all: yes
        password: ""
        check_implicit_admin: yes
  when: false

handlers:
  - name: restart mysql
    service:
      name: mysql
      state: restarted
